// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_bnIXrbMvREa0rRxG7ETc_qhk3sE1tP4',
    appId: '1:255452747282:web:1c42266d92e607c899eacb',
    messagingSenderId: '255452747282',
    projectId: 'taxi-chrono-firebase',
    authDomain: 'taxi-chrono-firebase.firebaseapp.com',
    databaseURL: 'https://taxi-chrono-firebase-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'taxi-chrono-firebase.appspot.com',
    measurementId: 'G-KF47VNVX87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx0VVYSYc3OgedqVZ94DkkpN55QMlvaM4',
    appId: '1:255452747282:android:1234326ff464ecba99eacb',
    messagingSenderId: '255452747282',
    projectId: 'taxi-chrono-firebase',
    databaseURL: 'https://taxi-chrono-firebase-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'taxi-chrono-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj3_GGcwwzvU7o9eMoZVfTCaMYAodBAVY',
    appId: '1:255452747282:ios:88a2c681903ab58499eacb',
    messagingSenderId: '255452747282',
    projectId: 'taxi-chrono-firebase',
    databaseURL: 'https://taxi-chrono-firebase-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'taxi-chrono-firebase.appspot.com',
    iosBundleId: 'com.incc.taxischrono.app',
  );
}
